#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

export TEMP_SERVICE_FILE=temp.service

if [[ ! -f ${TEMP_SERVICE_FILE} ]]; then
    echo -e "----------------------------------------------------"
    echo -e "${YELLOW}${TEMP_SERVICE_FILE}${LIGHT_RED} not found!$NC"
    echo -e "----------------------------------------------------"
    echo -e "The simplest solution is to get a fresh copy of"
    echo -e "${YELLOW}${TEMP_SERVICE_FILE}${NC} and try again. Here is one way to"
    echo -e "get a fresh copy:"
    echo -e "${LIGHT_GREEN}wget https://raw.githubusercontent.com/charliecalvert/elven-systemd-tools/master/temp.service${NC}"
    echo -e "----------------------------------------------------"
    exit 1
fi

source setup-environment-service
echo -e "Renaming$YELLOW ${TEMP_SERVICE_FILE}$NC to $YELLOW$SYSTEMD_PROJECT_NAME.service"$NC
cp ${TEMP_SERVICE_FILE} $SYSTEMD_PROJECT_NAME.service
./mod-service
./setup-service
./check-service
