#!/bin/bash

LOCAL_IP=$(./get-ip.js)

function banner {
    echo ' '
    echo ===============================
    echo --- "$1" ---
    echo ===============================
}

function show {
    banner "$1"
    sudo systemctl show -p ActiveState -p SubState -p Environment $2
}

function showSystemCheck() {
    show 'SystemCheck' systemcheck.service
}

function showSystemCheckRefactor {
    show 'SystemCheckRefactor' systemcheck.service
}

function showAWSProvision {
    show 'Aws Provision' systemcheck.service
}

function showMidterm {
    show 'Midterm' systemcheck.service
}

function showEc2CopyFile {
    show 'EC2-Copy-File' systemcheck.service
}

function checkPorts() {
    sudo nmap -p 30025-30235 ${LOCAL_IP}
}

echo 'System Service Control'

echo 'Learn about Systemd and other running services.'

while true; do
    echo -e "$LIGHT_BLUE Menu"    
    echo -e "$LIGHT_GREEN  a) Check Ports 30025-30040"
    echo -e "$LIGHT_GREEN  b) SystemCheck"
    echo -e "$LIGHT_GREEN  c) SystemCheckRefactor"
    echo -e "$LIGHT_GREEN  d) AWS Provision"
    echo -e "$LIGHT_GREEN  e) Midterm"
    echo -e "$LIGHT_GREEN  f) EC2-Copy-File"
    echo -e "$LIGHT_RED  x) Exit"
    echo -e "\n$NC"

    read -p "Please make a selection: " userInput
    case $userInput in
        [Aa]* ) checkPorts false; continue;;
        [Bb]* ) showSystemCheck; continue;;
        [Cc]* ) showSystemCheckRefactor; continue;;
        [Dd]* ) showAWSProvision; continue;;
        [Ee]* ) showMidterm; continue;;
        [Ff]* ) showEc2CopyFile; continue;;
        [XxQq]* ) break;;
        *) echo -e "\n$NC" + "Please answer with a, b, c, or x.";;
    esac
done
